package javaapplication16;
// Generated 04.Tem.2013 21:10:49 by Hibernate Tools 3.2.1.GA



/**
 * Rezervasyon generated by hbm2java
 */
public class Rezervasyon  implements java.io.Serializable {


     private Integer id;
     private String isim;
     private int fiyat;

    public Rezervasyon() {
    }

    public Rezervasyon(String isim, int fiyat) {
       this.isim = isim;
       this.fiyat = fiyat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIsim() {
        return this.isim;
    }
    
    public void setIsim(String isim) {
        this.isim = isim;
    }
    public int getFiyat() {
        return this.fiyat;
    }
    
    public void setFiyat(int fiyat) {
        this.fiyat = fiyat;
    }




}


