package cehars;
// Generated 09.Tem.2013 13:19:59 by Hibernate Tools 3.2.1.GA



/**
 * Rezervasyon generated by hbm2java
 */
public class Rezervasyon  implements java.io.Serializable {


     private String isim;

    public Rezervasyon() {
    }

    public Rezervasyon(String isim) {
       this.isim = isim;
    }
   
    public String getIsim() {
        return this.isim;
    }
    
    public void setIsim(String isim) {
        this.isim = isim;
    }




}


